import Head from 'next/head';
import { Layout } from '@/components/common';
import { HomePage } from '@/components/pages/home/Home.page';
import { Footer } from '@/components/common/footer/Footer';

export default function Home() {
	return (
		<>
			<Head>
				<title>Nexter Seen</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout title={'Nexter seen'}>
				<HomePage />
			</Layout>
			<footer>
				<Footer />
			</footer>
		</>
	);
}
