name: Codeball

on: [pull_request]

jobs:
  codeball-review:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    name: Run Codeball Code Review
    steps:
      - name: Codeball AI Actions
        uses: sturdy-dev/codeball-action@v2
        with:
          approvePullRequests: "false"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "true"
          failJobsWhenReviewNeeded: "false"
